import type { ModuleConfig } from "./types";

export const modules: ModuleConfig[] = [
  {
    id: "dp",
    title: "Dynamic Programming",
    shortTitle: "DP",
    tagline: "It's just remembering answers you already figured out",
    description: "Master the most feared interview topic. Watch recursion trees explode, then collapse them with memoization. From Fibonacci to Knapsack — visually, step by step.",
    color: {
      gradient: "from-blue-500 to-violet-600",
      bg: "bg-blue-50",
      text: "text-blue-700",
      accent: "bg-blue-500",
      border: "border-blue-200",
    },
    topics: ["Fibonacci", "Climbing Stairs", "Grid Paths", "Coin Change", "Knapsack"],
    status: "available",
    problemCount: 5,
    practiceCount: 10,
  },
  {
    id: "graphs",
    title: "Graph Algorithms",
    shortTitle: "Graphs",
    tagline: "Navigate nodes and edges like a pro",
    description: "Visualize BFS and DFS traversals, understand topological ordering, and watch Dijkstra find shortest paths — all animated on interactive graphs.",
    color: {
      gradient: "from-emerald-500 to-teal-600",
      bg: "bg-emerald-50",
      text: "text-emerald-700",
      accent: "bg-emerald-500",
      border: "border-emerald-200",
    },
    topics: ["BFS", "DFS", "Topological Sort", "Dijkstra's Algorithm"],
    status: "available",
    problemCount: 4,
    practiceCount: 0,
  },
  {
    id: "backtracking",
    title: "Backtracking",
    shortTitle: "Backtrack",
    tagline: "Explore, prune, and conquer",
    description: "Watch decision trees grow and branches get pruned in real time. From generating permutations to solving N-Queens — see how constraints eliminate possibilities.",
    color: {
      gradient: "from-amber-500 to-orange-600",
      bg: "bg-amber-50",
      text: "text-amber-700",
      accent: "bg-amber-500",
      border: "border-amber-200",
    },
    topics: ["Permutations", "Subsets", "N-Queens", "Sudoku Solver"],
    status: "coming-soon",
    problemCount: 0,
    practiceCount: 0,
  },
  {
    id: "binary-search",
    title: "Binary Search",
    shortTitle: "BinSearch",
    tagline: "Half the problem, every single step",
    description: "It's not just sorted arrays. Learn to binary search on answer spaces, find boundaries, and solve problems you'd never expect with O(log n) thinking.",
    color: {
      gradient: "from-cyan-500 to-blue-600",
      bg: "bg-cyan-50",
      text: "text-cyan-700",
      accent: "bg-cyan-500",
      border: "border-cyan-200",
    },
    topics: ["Sorted Array Search", "Search Space Problems", "Bisect on Answer", "Finding Boundaries"],
    status: "coming-soon",
    problemCount: 0,
    practiceCount: 0,
  },
  {
    id: "sliding-window",
    title: "Sliding Window & Two Pointers",
    shortTitle: "Window",
    tagline: "Move smart, not hard",
    description: "Watch pointers glide across arrays in real time. Fixed windows, variable windows, and two-pointer techniques — the patterns behind countless interview questions.",
    color: {
      gradient: "from-pink-500 to-rose-600",
      bg: "bg-pink-50",
      text: "text-pink-700",
      accent: "bg-pink-500",
      border: "border-pink-200",
    },
    topics: ["Fixed Window", "Variable Window", "Two Pointers", "Shrink & Expand"],
    status: "coming-soon",
    problemCount: 0,
    practiceCount: 0,
  },
  {
    id: "heaps-greedy",
    title: "Heaps & Greedy",
    shortTitle: "Heaps",
    tagline: "The right choice at every step",
    description: "Priority queues, interval scheduling, and greedy strategies. Learn when local optimization gives global results — and when it doesn't (that's where DP kicks in).",
    color: {
      gradient: "from-violet-500 to-purple-600",
      bg: "bg-violet-50",
      text: "text-violet-700",
      accent: "bg-violet-500",
      border: "border-violet-200",
    },
    topics: ["Priority Queues", "Top-K Problems", "Interval Scheduling", "Greedy vs DP"],
    status: "coming-soon",
    problemCount: 0,
    practiceCount: 0,
  },
];

export function getModule(id: string): ModuleConfig | undefined {
  return modules.find((m) => m.id === id);
}
