import type { DailyProblem } from "../components/DailyChallenge";

export const dailyProblems: DailyProblem[] = [
  {
    id: "daily-1",
    title: "Contains Duplicate",
    description: "Given an integer array, return true if any value appears at least twice.",
    difficulty: "Easy",
    functionName: "hasDuplicate",
    starterJS: `function hasDuplicate(nums) {\n  // Return true if any value appears twice\n\n}`,
    testCases: [
      { input: [[1, 2, 3, 1]], expected: true, label: "[1,2,3,1] → true" },
      { input: [[1, 2, 3, 4]], expected: false, label: "[1,2,3,4] → false" },
      { input: [[1, 1, 1, 3, 3, 4, 3, 2, 4, 2]], expected: true, label: "many duplicates → true" },
    ],
    hint: "A Set only stores unique values. If the Set size is less than the array length...",
  },
  {
    id: "daily-2",
    title: "Maximum Subarray",
    description: "Find the contiguous subarray with the largest sum (Kadane's algorithm).",
    difficulty: "Easy",
    functionName: "maxSubArray",
    starterJS: `function maxSubArray(nums) {\n  // Return the maximum subarray sum\n\n}`,
    testCases: [
      { input: [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], expected: 6, label: "mixed → 6" },
      { input: [[1]], expected: 1, label: "[1] → 1" },
      { input: [[-1]], expected: -1, label: "[-1] → -1" },
    ],
    hint: "Track current sum and max sum. If current sum goes negative, reset to 0.",
  },
  {
    id: "daily-3",
    title: "Palindrome Check",
    description: "Check if a string reads the same forwards and backwards (letters only, case-insensitive).",
    difficulty: "Easy",
    functionName: "isPalindrome",
    starterJS: `function isPalindrome(s) {\n  // Return true if s is a palindrome\n  // Ignore non-letter characters, case-insensitive\n\n}`,
    testCases: [
      { input: ["A man, a plan, a canal: Panama"], expected: true, label: "Panama → true" },
      { input: ["race a car"], expected: false, label: "race a car → false" },
      { input: [""], expected: true, label: "empty → true" },
    ],
    hint: "Filter out non-alphanumeric characters, lowercase everything, then compare with its reverse.",
  },
  {
    id: "daily-4",
    title: "Product of Array Except Self",
    description: "Given nums, return an array where answer[i] is the product of all elements except nums[i]. No division allowed.",
    difficulty: "Medium",
    functionName: "productExceptSelf",
    starterJS: `function productExceptSelf(nums) {\n  // Return array of products excluding self\n  // No division!\n\n}`,
    testCases: [
      { input: [[1, 2, 3, 4]], expected: [24, 12, 8, 6], label: "[1,2,3,4] → [24,12,8,6]" },
      { input: [[-1, 1, 0, -3, 3]], expected: [0, 0, 9, 0, 0], label: "with zero" },
    ],
    hint: "Two passes: left-to-right accumulating prefix products, then right-to-left for suffix products.",
  },
  {
    id: "daily-5",
    title: "Climbing Stairs",
    description: "You can climb 1 or 2 steps. How many distinct ways to reach step n?",
    difficulty: "Easy",
    functionName: "climbStairs",
    starterJS: `function climbStairs(n) {\n  // Return number of ways to climb n steps\n\n}`,
    testCases: [
      { input: [2], expected: 2, label: "2 → 2" },
      { input: [3], expected: 3, label: "3 → 3" },
      { input: [5], expected: 8, label: "5 → 8" },
      { input: [40], expected: 165580141, label: "40 → needs DP!" },
    ],
    hint: "It's Fibonacci! dp[i] = dp[i-1] + dp[i-2].",
  },
  {
    id: "daily-6",
    title: "Valid Anagram",
    description: "Given two strings, return true if they are anagrams of each other.",
    difficulty: "Easy",
    functionName: "isAnagram",
    starterJS: `function isAnagram(s, t) {\n  // Return true if s and t are anagrams\n\n}`,
    testCases: [
      { input: ["anagram", "nagaram"], expected: true, label: "anagram → true" },
      { input: ["rat", "car"], expected: false, label: "rat/car → false" },
      { input: ["a", "a"], expected: true, label: "single char → true" },
    ],
    hint: "Count character frequencies in both strings and compare. Or sort both and check equality.",
  },
  {
    id: "daily-7",
    title: "Merge Intervals",
    description: "Given an array of intervals [start, end], merge all overlapping intervals.",
    difficulty: "Medium",
    functionName: "merge",
    starterJS: `function merge(intervals) {\n  // Return merged non-overlapping intervals\n\n}`,
    testCases: [
      { input: [[[1, 3], [2, 6], [8, 10], [15, 18]]], expected: [[1, 6], [8, 10], [15, 18]], label: "overlapping" },
      { input: [[[1, 4], [4, 5]]], expected: [[1, 5]], label: "touching" },
    ],
    hint: "Sort by start time. Then iterate: if current overlaps with last merged, extend the end. Otherwise, add new interval.",
  },
  {
    id: "daily-8",
    title: "Number of Islands",
    description: "Given a 2D grid of '1' (land) and '0' (water), count the number of islands.",
    difficulty: "Medium",
    functionName: "numIslands",
    starterJS: `function numIslands(grid) {\n  // Count connected components of '1's\n\n}`,
    testCases: [
      { input: [[["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]]], expected: 3, label: "3 islands" },
      { input: [[["1","1","1"],["0","1","0"],["1","1","1"]]], expected: 1, label: "1 island" },
    ],
    hint: "For each unvisited '1', start a BFS/DFS to mark all connected '1's. Each new search = one island.",
  },
  {
    id: "daily-9",
    title: "Rotate Array",
    description: "Rotate array to the right by k steps. Do it in-place.",
    difficulty: "Easy",
    functionName: "rotate",
    starterJS: `function rotate(nums, k) {\n  // Rotate nums right by k steps, return the result\n\n}`,
    testCases: [
      { input: [[1, 2, 3, 4, 5, 6, 7], 3], expected: [5, 6, 7, 1, 2, 3, 4], label: "rotate by 3" },
      { input: [[-1, -100, 3, 99], 2], expected: [3, 99, -1, -100], label: "rotate by 2" },
    ],
    hint: "Reverse the entire array, then reverse first k elements, then reverse the rest. Or: splice and concat.",
  },
  {
    id: "daily-10",
    title: "Coin Change",
    description: "Given coins and an amount, return the fewest coins needed. Return -1 if impossible.",
    difficulty: "Medium",
    functionName: "coinChange",
    starterJS: `function coinChange(coins, amount) {\n  // Return min coins to make amount, or -1\n\n}`,
    testCases: [
      { input: [[1, 5, 10, 25], 30], expected: 2, label: "30 cents → 2 coins" },
      { input: [[2], 3], expected: -1, label: "impossible → -1" },
      { input: [[1], 0], expected: 0, label: "0 → 0 coins" },
      { input: [[1, 2, 5], 100], expected: 20, label: "100 → needs DP!" },
    ],
    hint: "DP: dp[i] = min coins for amount i. For each amount, try each coin: dp[i] = min(dp[i], dp[i-coin] + 1).",
  },
];
