import type { InterviewProblem } from "../components/InterviewSim";

export const interviewProblems: InterviewProblem[] = [
  {
    id: "interview-1",
    title: "Maximum Profit",
    description: "You're given an array of stock prices where prices[i] is the price on day i. Find the maximum profit from buying on one day and selling on a later day. You can only make one transaction.",
    constraints: ["1 ≤ prices.length ≤ 10⁵", "0 ≤ prices[i] ≤ 10⁴"],
    patterns: ["Dynamic Programming", "Two Pointers", "Greedy / Single Pass", "Divide and Conquer"],
    correctPattern: "Greedy / Single Pass",
    testCases: [
      { input: [[7, 1, 5, 3, 6, 4]], expected: 5, label: "maxProfit([7,1,5,3,6,4]) = 5" },
      { input: [[7, 6, 4, 3, 1]], expected: 0, label: "maxProfit([7,6,4,3,1]) = 0" },
      { input: [[2, 4, 1]], expected: 2, label: "maxProfit([2,4,1]) = 2" },
    ],
    functionName: "maxProfit",
    starterJS: `function maxProfit(prices) {\n  // Return max profit from one buy + sell\n\n}`,
    solutionJS: `function maxProfit(prices) {\n  let min = Infinity, profit = 0;\n  for (const p of prices) {\n    min = Math.min(min, p);\n    profit = Math.max(profit, p - min);\n  }\n  return profit;\n}`,
    optimalTime: "O(n)",
    optimalSpace: "O(1)",
    timeLimit: 15,
    difficulty: "Medium",
  },
  {
    id: "interview-2",
    title: "Word Break",
    description: "Given a string s and a dictionary of words, determine if s can be segmented into space-separated words that are all in the dictionary. You can reuse dictionary words.",
    constraints: ["1 ≤ s.length ≤ 300", "1 ≤ wordDict.length ≤ 1000"],
    patterns: ["BFS", "Dynamic Programming", "Backtracking", "Trie"],
    correctPattern: "Dynamic Programming",
    testCases: [
      { input: ["leetcode", ["leet", "code"]], expected: true, label: 'wordBreak("leetcode") = true' },
      { input: ["applepenapple", ["apple", "pen"]], expected: true, label: 'wordBreak("applepenapple") = true' },
      { input: ["catsandog", ["cats", "dog", "sand", "and", "cat"]], expected: false, label: 'wordBreak("catsandog") = false' },
    ],
    functionName: "wordBreak",
    starterJS: `function wordBreak(s, wordDict) {\n  // Return true if s can be segmented into dictionary words\n\n}`,
    solutionJS: `function wordBreak(s, wordDict) {\n  const set = new Set(wordDict);\n  const dp = new Array(s.length + 1).fill(false);\n  dp[0] = true;\n  for (let i = 1; i <= s.length; i++) {\n    for (let j = 0; j < i; j++) {\n      if (dp[j] && set.has(s.substring(j, i))) {\n        dp[i] = true;\n        break;\n      }\n    }\n  }\n  return dp[s.length];\n}`,
    optimalTime: "O(n²)",
    optimalSpace: "O(n)",
    timeLimit: 20,
    difficulty: "Medium",
  },
  {
    id: "interview-3",
    title: "Course Schedule",
    description: "There are numCourses courses labeled 0 to numCourses-1. You're given prerequisite pairs [a, b] meaning you must take course b before course a. Return true if you can finish all courses.",
    constraints: ["1 ≤ numCourses ≤ 2000", "0 ≤ prerequisites.length ≤ 5000"],
    patterns: ["Topological Sort", "BFS", "Union Find", "Dynamic Programming"],
    correctPattern: "Topological Sort",
    testCases: [
      { input: [2, [[1, 0]]], expected: true, label: "canFinish(2, [[1,0]]) = true" },
      { input: [2, [[1, 0], [0, 1]]], expected: false, label: "canFinish(2, [[1,0],[0,1]]) = false" },
      { input: [3, [[1, 0], [2, 1]]], expected: true, label: "canFinish(3, [[1,0],[2,1]]) = true" },
    ],
    functionName: "canFinish",
    starterJS: `function canFinish(numCourses, prerequisites) {\n  // Return true if all courses can be completed\n\n}`,
    solutionJS: `function canFinish(numCourses, prerequisites) {\n  const graph = Array.from({length: numCourses}, () => []);\n  const inDeg = new Array(numCourses).fill(0);\n  for (const [a, b] of prerequisites) {\n    graph[b].push(a);\n    inDeg[a]++;\n  }\n  const queue = [];\n  for (let i = 0; i < numCourses; i++) if (inDeg[i] === 0) queue.push(i);\n  let count = 0;\n  while (queue.length) {\n    const node = queue.shift();\n    count++;\n    for (const nb of graph[node]) {\n      inDeg[nb]--;\n      if (inDeg[nb] === 0) queue.push(nb);\n    }\n  }\n  return count === numCourses;\n}`,
    optimalTime: "O(n)",
    optimalSpace: "O(n)",
    timeLimit: 20,
    difficulty: "Medium",
  },
];
