import type { DrillProblem } from "../components/SpeedDrill";

export const speedDrillProblems: DrillProblem[] = [
  {
    id: "drill-reverse",
    title: "Reverse Array",
    description: "Reverse an array in-place and return it.",
    timeLimit: 45,
    functionName: "reverse",
    starterJS: `function reverse(arr) {\n  // Reverse arr in-place\n\n}`,
    testCases: [
      { input: [[1, 2, 3]], expected: [3, 2, 1], label: "reverse([1,2,3])" },
      { input: [[1]], expected: [1], label: "reverse([1])" },
      { input: [[5, 4, 3, 2, 1]], expected: [1, 2, 3, 4, 5], label: "reverse([5,4,3,2,1])" },
    ],
    difficulty: "Easy",
  },
  {
    id: "drill-twosum",
    title: "Two Sum",
    description: "Return indices of two numbers that add up to target.",
    timeLimit: 60,
    functionName: "twoSum",
    starterJS: `function twoSum(nums, target) {\n  // Return [i, j] where nums[i] + nums[j] === target\n\n}`,
    testCases: [
      { input: [[2, 7, 11, 15], 9], expected: [0, 1], label: "twoSum([2,7,11,15], 9)" },
      { input: [[3, 2, 4], 6], expected: [1, 2], label: "twoSum([3,2,4], 6)" },
    ],
    difficulty: "Easy",
  },
  {
    id: "drill-maxsubarray",
    title: "Max Subarray Sum",
    description: "Find the contiguous subarray with the largest sum (Kadane's algorithm).",
    timeLimit: 75,
    functionName: "maxSubArray",
    starterJS: `function maxSubArray(nums) {\n  // Return the maximum subarray sum\n\n}`,
    testCases: [
      { input: [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], expected: 6, label: "maxSubArray([-2,1,-3,4,-1,2,1,-5,4])" },
      { input: [[1]], expected: 1, label: "maxSubArray([1])" },
      { input: [[-1, -2, -3]], expected: -1, label: "maxSubArray([-1,-2,-3])" },
    ],
    difficulty: "Easy",
  },
  {
    id: "drill-valid-parens",
    title: "Valid Parentheses",
    description: "Check if a string of brackets is valid: (), [], {}.",
    timeLimit: 75,
    functionName: "isValid",
    starterJS: `function isValid(s) {\n  // Return true if brackets are balanced\n\n}`,
    testCases: [
      { input: ["()[]{}"], expected: true, label: 'isValid("()[]{}") = true' },
      { input: ["(]"], expected: false, label: 'isValid("(]") = false' },
      { input: ["([)]"], expected: false, label: 'isValid("([)]") = false' },
      { input: ["{[]}"], expected: true, label: 'isValid("{[]}") = true' },
    ],
    difficulty: "Easy",
  },
  {
    id: "drill-merge-sorted",
    title: "Merge Two Sorted Arrays",
    description: "Merge two sorted arrays into one sorted array.",
    timeLimit: 60,
    functionName: "merge",
    starterJS: `function merge(a, b) {\n  // Return a new sorted array from two sorted inputs\n\n}`,
    testCases: [
      { input: [[1, 3, 5], [2, 4, 6]], expected: [1, 2, 3, 4, 5, 6], label: "merge([1,3,5],[2,4,6])" },
      { input: [[], [1, 2]], expected: [1, 2], label: "merge([],[1,2])" },
      { input: [[1], []], expected: [1], label: "merge([1],[])" },
    ],
    difficulty: "Easy",
  },
  {
    id: "drill-fib-dp",
    title: "Fibonacci (DP)",
    description: "Return the nth Fibonacci number. Must handle n=40+ efficiently.",
    timeLimit: 45,
    functionName: "fib",
    starterJS: `function fib(n) {\n  // Return nth Fibonacci number (0-indexed)\n\n}`,
    testCases: [
      { input: [0], expected: 0, label: "fib(0) = 0" },
      { input: [10], expected: 55, label: "fib(10) = 55" },
      { input: [40], expected: 102334155, label: "fib(40) — needs DP!" },
    ],
    difficulty: "Easy",
  },
  {
    id: "drill-bfs",
    title: "BFS Traversal",
    description: "Return nodes in BFS order from start node.",
    timeLimit: 90,
    functionName: "bfs",
    starterJS: `function bfs(graph, start) {\n  // Return array of nodes in BFS order\n  // graph = { A: ["B","C"], B: ["A"], ... }\n\n}`,
    testCases: [
      { input: [{ A: ["B", "C"], B: ["A"], C: ["A"] }, "A"], expected: ["A", "B", "C"], label: "bfs(triangle, A)" },
      { input: [{ X: [] }, "X"], expected: ["X"], label: "bfs(single, X)" },
    ],
    difficulty: "Medium",
  },
  {
    id: "drill-binary-search",
    title: "Binary Search",
    description: "Find index of target in sorted array, or -1.",
    timeLimit: 60,
    functionName: "search",
    starterJS: `function search(nums, target) {\n  // Return index of target or -1\n\n}`,
    testCases: [
      { input: [[-1, 0, 3, 5, 9, 12], 9], expected: 4, label: "search([...], 9) = 4" },
      { input: [[-1, 0, 3, 5, 9, 12], 2], expected: -1, label: "search([...], 2) = -1" },
      { input: [[5], 5], expected: 0, label: "search([5], 5) = 0" },
    ],
    difficulty: "Easy",
  },
];
